import json
from datetime import datetime
import urllib.request
import urllib.error


def _call_ollama(prompt: str) -> str:
    try:
        data = json.dumps({
            "model": "llama3",
            "prompt": prompt,
            "stream": False
        }).encode("utf-8")

        req = urllib.request.Request(
            "http://localhost:11434/api/generate",
            data=data,
            headers={"Content-Type": "application/json"}
        )
        with urllib.request.urlopen(req, timeout=30) as response:
            result = json.loads(response.read().decode("utf-8"))
            return result.get("response", "").strip()
    except Exception as e:
        print(f"[alert_generator] Ollama unavailable, using template fallback: {e}")
        return None


def _template_alert(device: str, issue: str, diagnosis: dict) -> str:
    if not diagnosis or not diagnosis.get("matched"):
        return f"""INCIDENT ALERT - {device}
Issue: {issue}

Status: No confident match found in knowledge base.
This incident requires manual engineer review.

Generated by NetMind AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""

    top_cause = diagnosis["causes"][0]
    evidence_lines = []
    for i, c in enumerate(diagnosis["causes"], 1):
        evidence_lines.append(f"  {i}. {c['cause']} ({c['probability']}% probability match)")
    evidence = "\n".join(evidence_lines)

    return f"""INCIDENT ALERT - {device}

Issue Reported:
{issue}

Root Cause (Most Likely):
{top_cause['cause']} - {top_cause['probability']}% confidence

How This Was Identified:
Matched against knowledge base using symptom analysis.
Ranked candidate causes:
{evidence}

Recommended Solution Steps:
{top_cause['troubleshooting_steps']}

Verification Command:
{top_cause['verification_command']}

Status: Auto-diagnosed by NetMind AI - pending engineer confirmation.
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""


def generate_alert(device: str, issue: str, diagnosis: dict) -> str:
    template = _template_alert(device, issue, diagnosis)

    if not diagnosis or not diagnosis.get("matched"):
        return template

    prompt = f"""Rewrite the following network incident alert in clear, professional prose 
suitable for a network operations manager. Keep all facts, numbers, and commands exactly 
as given. Keep it concise - 4-6 sentences plus the verification command on its own line. 
Do not invent any information not present below.

{template}

Rewritten professional version:"""

    llm_response = _call_ollama(prompt)

    if llm_response:
        return llm_response + f"\n\nVerification Command: {diagnosis['causes'][0]['verification_command']}"
    else:
        return template