from datetime import datetime


def generate_alert(device: str, issue: str, diagnosis: dict) -> str:
    if not diagnosis or not diagnosis.get("matched"):
        return f"""INCIDENT ALERT — {device}
Issue: {issue}

Status: No confident match found in knowledge base.
This incident requires manual engineer review.

Generated by NetMind AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""

    top_cause = diagnosis["causes"][0]

    evidence_lines = []
    for i, c in enumerate(diagnosis["causes"], 1):
        evidence_lines.append(f"  {i}. {c['cause']} ({c['probability']}% probability match)")
    evidence = "\n".join(evidence_lines)

    steps = top_cause["troubleshooting_steps"]

    message = f"""INCIDENT ALERT — {device}

Issue Reported:
{issue}

Root Cause (Most Likely):
{top_cause['cause']} — {top_cause['probability']}% confidence

How This Was Identified:
Matched against knowledge base using symptom and keyword analysis.
Ranked candidate causes:
{evidence}

Recommended Solution Steps:
{steps}

Verification Command:
{top_cause['verification_command']}

Status: Auto-diagnosed by NetMind AI — pending engineer confirmation.
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""
    return message