from datetime import datetime
import os
import subprocess
from typing import Optional


def _polish_with_ollama(text: str, model: Optional[str] = None, timeout: int = 15) -> str:
    """Try to rewrite `text` using a local Ollama model. On any failure, return the original text.

    The model name may be supplied via `model` or the `OLLAMA_MODEL` env var. If the
    `ollama` CLI isn't installed or the command fails, we fall back to the template.
    """
    model = model or os.environ.get("OLLAMA_MODEL", "llama3")
    # Instruction: preserve technical details and steps, produce concise professional prose
    prompt = (
        "Rewrite the following incident alert into clear, natural, professional prose "
        "suitable for engineers and on-call staff. Keep all technical details, steps, and "
        "verification commands. Produce a concise but comprehensive alert:\n\n" + text
    )
    try:
        # Use the Ollama CLI if available. Examples of usage vary; passing the prompt
        # as the final positional argument works with typical Ollama installs.
        proc = subprocess.run(["ollama", "run", model, prompt], capture_output=True, text=True, timeout=timeout)
        if proc.returncode == 0 and proc.stdout.strip():
            return proc.stdout.strip()
    except FileNotFoundError:
        # `ollama` not installed / not in PATH
        pass
    except Exception:
        # Any other error (timeout, runtime error) — fall back to template
        pass
    return text


def generate_alert(device: str, issue: str, diagnosis: dict) -> str:
    if not diagnosis or not diagnosis.get("matched"):
        return f"""INCIDENT ALERT — {device}
Issue: {issue}

Status: No confident match found in knowledge base.
This incident requires manual engineer review.

Generated by NetMind AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""

    top_cause = diagnosis["causes"][0]

    evidence_lines = []
    for i, c in enumerate(diagnosis["causes"], 1):
        evidence_lines.append(f"  {i}. {c['cause']} ({c['probability']}% probability match)")
    evidence = "\n".join(evidence_lines)

    steps = top_cause["troubleshooting_steps"]

    structured_message = f"""INCIDENT ALERT — {device}

Issue Reported:
{issue}

Root Cause (Most Likely):
{top_cause['cause']} — {top_cause['probability']}% confidence

How This Was Identified:
Matched against knowledge base using symptom and keyword analysis.
Ranked candidate causes:
{evidence}

Recommended Solution Steps:
{steps}

Verification Command:
{top_cause['verification_command']}

Status: Auto-diagnosed by NetMind AI — pending engineer confirmation.
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""

    # Attempt to polish with Ollama; fall back to the structured template if Ollama isn't reachable
    polished = _polish_with_ollama(structured_message)
    return polished